max_reselect_num: 3

questions:
  - type: 専門・職能別コンピタンス
    text: 「このこのならあの人に聞け」と絶えず専門家としてのアドバイスを求められる分野でうまくやっていくことをめざす。
  - type: 全般管理コンピタンス
    text: 他の人々のやる気をまとめあげ、チームをマネジメントすることによって大きな成果を上げることが出来たときに、最も大きな充実感を仕事に感じる。
  - type: 自律・独立
    text: 自分のやり方、自分のスケジュール通りに、自由に仕事ができるようなキャリアを目指す。
  - type: 保障・安定
    text: 自由や自律を勝ち取るよりも、将来の保障や安定を得ることが、自分にとってはより重要なことだ。
  - type: 起業家的創造性
    text: 常に自分の事業を起こすことができそうなアイデアを探している。
  - type: 奉仕・社会貢献
    text: 社会に本当に貢献できていると感じれるときにこそ、キャリアがうまくいきそうだと感じる。
  - type: 純粋な挑戦
    text: 難題を解決したり、とてつもない挑戦課題にみまわれた状況を打破したりできるようなキャリアをめざす。
  - type: 生活様式（ライフスタイル)
    text: 家族とともに楽しみにしていることが犠牲になってしまう仕事に異動させられるぐらいなら、その組織をやめた方がましだ。
  - type: 専門・職能別コンピタンス
    text: キャリアを通じて専門技能や職能分野の技能をすごく高度に磨き上げることができるならキャリアがうまくいきそうだと感じる。
  - type: 全般管理コンピタンス
    text: 複雑な組織を率い、大勢の人々を左右する意思決定を自分で下すような立場を目指す。
  - type: 自律・独立
    text: どのような課題をどのような日程と手順でおこなうのか、について自分の思い通りになるとき、最も大きな充実感を仕事に感じる。
  - type: 保障・安定
    text: 安定した職務保障もなしに仕事に配属されるくらいなら、すっぱりとその組織を離れるだろう。
  - type: 起業家的創造性
    text: 他人の経営する組織でマネージャーとして高い職位につくよりも、むしろ自分の事業を起こすことを重視する。
  - type: 奉仕・社会貢献
    text: キャリアを通じて、他の人々のために自分の才能を役立てることが出来たときに、最も大きな充実感を自分のキャリアに感じる。
  - type: 純粋な挑戦
    text: 非常に難しい挑戦課題に直面し、それを克服できたときにこそ、キャリアがうまくいきそうだと感じる。
  - type: 生活様式（ライフスタイル)
    text: 自分が家族がらみで望んでいることと、仕事から要請されることとがうまく両立できるキャリアを目指す。
  - type: 専門・職能別コンピタンス
    text: ゼネラル・マネージャー（部門長）になるよりも、自分の専門職能分野で上級マネージャーになる方が、より魅力的に感じられる。
  - type: 全般管理コンピタンス
    text: 何らかの組織でゼネラル・マネージャー（部門長）の立場で仕事をするときにこそ、キャリアがうまくいきそうだと感じる。
  - type: 自律・独立
    text: 完全な自律や自由を獲得したときにこそ、キャリアがうまくいきそうだと感じる。
  - type: 保障・安定
    text: 将来が安定していて、安心感のもてる会社での仕事を求めている。
  - type: 起業家的創造性
    text: 自分自身のアイデアと努力だけによって何かを創り上げたときに、最も大きな充実感を自分のキャリアに感じる。
  - type: 奉仕・社会貢献
    text: マネージャーとして高い職位につくことよりも、自分の技能を生かして少しでも世の中を住みやすく働きやすくする方が、もっとも大切だと思う。
  - type: 純粋な挑戦
    text: 一見解決不可能と思われた問題を解決したり、どうにもならないような局面を打開したとき、最も大きな充実感を自分のキャリアに感じる。
  - type: 生活様式（ライフスタイル)
    text: 自分の個人的な要望、家族からの要望、キャリアに求められることをうまくバランスさせることができたときにこそ、キャリアがうまくいきそうだと感じる。
  - type: 専門・職能別コンピタンス
    text: 自分の専門領域からはずれてしまうような人事異動をローテーションとして受け入れるくらいなら、むしろその組織をやめる。
  - type: 全般管理コンピタンス
    text: 今の自分の専門職脳領域で上級マネージャーになるよりも、ゼネラル・マネージャー（部門長）として仕事をする方が魅力的だと思う。
  - type: 自律・独立
    text: 将来が保証された安心なことよりも、規則や規律にしばられず、自分のやりたいように仕事ができるチャンスが大切だと思う。
  - type: 保障・安定
    text: 収入面、雇用面で完全に保証されていると感じられるときに、最も大きな充実感を仕事に感じる。
  - type: 起業家的創造性
    text: 自分自身の生み出した製品やアイデアで何かを創り出し、軌道にのせたときこそ、キャリアがうまくいきそうだと感じる。
  - type: 奉仕・社会貢献
    text: 人類や社会にほんとうの貢献ができるキャリアを目指す。
  - type: 純粋な挑戦
    text: 自分の問題解決能力、競争に打ち勝つ能力をフルに活かせる挑戦機会を求めている。
  - type: 生活様式（ライフスタイル)
    text: マネージャーとして高い地位につくことよりも、自分の個人的な生活と仕事生活の両方をうまくバランスさせるほうが大切だと思う。
  - type: 専門・職能別コンピタンス
    text: 自分独自の技能や才能を活用できたときに、最も大きな充実感を仕事に感じる。
  - type: 全般管理コンピタンス
    text: ゼネラル・マネージャー（部門長）になるコースから外れてしまいそうな仕事をやらされるぐらいなら、そんな組織はやめてしまう。
  - type: 自律・独立
    text: 自律して自由に行動できないような仕事につくくらいなら、そんな組織はやめてしまう。
  - type: 保障・安定
    text: 将来が保障され安心感を持って仕事に取り組めるようなキャリアを目指す。
  - type: 起業家的創造性
    text: 自分自身の事業を起こし、それを軌道にのせることを目指す。
  - type: 奉仕・社会貢献
    text: 他の人々の役に立つために能力を発揮することができないような配属を拝受するぐらいなら、その組織をやめたいと思う。
  - type: 純粋な挑戦
    text: ほとんど解決できそうもない問題に挑戦できるということは、マネージャーとして高い地位につくことよりももっと大切である。
  - type: 生活様式（ライフスタイル)
    text: 自分個人や家族の関心事にあまりマイナスの影響がないような仕事の機会をいつも求めている。
